services:
    app:
        build:
            args:
                user: ${USER}
                uid: 1000
            context: .
            dockerfile: docker/app.dockerfile
        # image: ${PROJECT_NAME}-app
        container_name: ${PROJECT_NAME}-app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        ports:
            - 5173:5173
        depends_on:
            - db
        volumes:
            - .:/var/www/html:delegated
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - network

    nginx:
        image: nginx:1.17-alpine
        container_name: ${PROJECT_NAME}-nginx
        restart: unless-stopped
        ports:
            - '${WEB_SERVER_PORT:-8080}:80'
        volumes:
            - .:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/nginx/log:/var/log/nginx
        networks:
            - network
# mysql
    db:
        image: 'mysql:8'
        container_name: ${PROJECT_NAME}-db
        restart: unless-stopped
        ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
          - '.:/var/www/html'
          - 'db_mysql:/var/lib/mysql'
        networks:
          - network
# phpmyadmin
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: ${PROJECT_NAME}-phpmyadmin
      restart: unless-stopped
      ports:
        - "8080:80"
      environment:
        - PMA_HOST=${DB_HOST}
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}
        - UPLOAD_LIMIT=30M
      depends_on:
        - db
      networks:
        - network
networks:
    network:
        driver: bridge
volumes:
#mysql
    db_mysql:
        driver: local
